### PR TITLE
use uuid.Must to wrap uuid.NewV4 which function return UUID instead o…

### PR DESCRIPTION
**Pull request by jumping**
use uuid.Must to wrap uuid.NewV4 which function return UUID instead of returning(UUID, error) by uuid.NewV4.

quzhengping@gmail.com

### CODE REVIEW

**Comment by ghost** [comment]
[CLA assistant check](https://cla.gocd.org/gocd-contrib/gocd-golang-agent?pullRequest=53) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.gocd.org/gocd-contrib/gocd-golang-agent?pullRequest=53) before we can accept your contribution.<br/><hr/>**Jumping Qu** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.gocd.org/check/gocd-contrib/gocd-golang-agent?pullRequest=53) it.</sub>

**Comment by barrowkwan** [comment]
hi @jumping are you able to sign the CLA so that we can merge your PR?  thanks

**Comment by jumping** [comment]
Actually I signed.
image

**Comment by barrowkwan** [comment]
HI @jumping can you click the recheck link ?  thanks

**Pull request closed without merging**
